export const dimensionMeta = {
  diagnosis: { label: "业务诊断", short: "诊断", code: "DIA" },
  scenario: { label: "场景判断", short: "场景", code: "SCN" },
  solution: { label: "方案构建", short: "方案", code: "SOL" },
  safety: { label: "风险边界", short: "边界", code: "SAFE" },
  delivery: { label: "推进交付", short: "交付", code: "DEL" },
};

export const questions = [
  {
    id: "q01",
    dimension: "diagnosis",
    scenario: "一家制造企业的老板希望尽快“上 AI 提效率”，但各部门对主要问题说法不一。",
    prompt: "你会怎样安排第一周？",
    options: [
      { text: "访谈部门负责人，整理各部门最急的自动化诉求", score: 3, signal: "管理访谈" },
      { text: "比较同业方案，估算采购成本和系统改造工作", score: 2, signal: "方案摸底" },
      { text: "跟踪两条高频流程，量化等待返工并确认责任人", score: 4, signal: "现场取证" },
      { text: "选择配合度高的部门，试用一款通用办公助手", score: 1, signal: "工具试用" },
    ],
  },
  {
    id: "q02",
    dimension: "diagnosis",
    scenario: "销售团队说“每天太忙，客户跟不过来”，负责人提出做自动跟进 Agent。",
    prompt: "哪个动作最能判断问题值不值得做？",
    options: [
      { text: "汇总销售的困难描述，按被提及次数确定优先级", score: 3, signal: "诉求归纳" },
      { text: "抽样还原线索阶段，记录耗时、等待和丢单证据", score: 4, signal: "流程证据" },
      { text: "检查 CRM 字段质量，估算接口接入和维护成本", score: 2, signal: "系统评估" },
      { text: "组织一次话术培训，观察团队是否愿意使用 AI", score: 1, signal: "采用试探" },
    ],
  },
  {
    id: "q03",
    dimension: "scenario",
    scenario: "电商客户提出商品文案、差评分析、库存预测和自动投流四个候选场景，首期只有六周。",
    prompt: "你会建议哪种首期组合？",
    options: [
      { text: "库存预测与差评分析，兼顾经营价值和用户反馈", score: 2, signal: "价值组合" },
      { text: "商品文案与库存预测，分别覆盖生成和预测能力", score: 3, signal: "能力组合" },
      { text: "自动投流与商品文案，优先改善增长侧的执行效率", score: 1, signal: "增长优先" },
      { text: "商品文案与差评分析，数据现成且结果容易复核", score: 4, signal: "可验试点" },
    ],
  },
  {
    id: "q04",
    dimension: "scenario",
    scenario: "知识库要回答售前问题，资料里存在两个仍在流转的价格版本，业务希望本周上线。",
    prompt: "你会怎样处理价格问答？",
    options: [
      { text: "确认权威来源和生效范围，再用冲突样本做上线测试", score: 4, signal: "版本治理" },
      { text: "按文件更新时间选择新版，同时在答案中标注日期", score: 3, signal: "时间推断" },
      { text: "同时检索两个版本，要求使用者自行判断适用价格", score: 2, signal: "并列呈现" },
      { text: "首期不回答价格问题，先开放其他产品信息问答", score: 1, signal: "范围规避" },
    ],
  },
  {
    id: "q05",
    dimension: "scenario",
    scenario: "团队从访谈中得到十个 AI 场景，但资源只够支持一个试点。",
    prompt: "哪组指标最适合决定先做什么？",
    options: [
      { text: "预算规模、管理层关注度、展示效果和上线速度", score: 2, signal: "资源导向" },
      { text: "模型能力、接口成熟度、开发工期和供应商支持", score: 3, signal: "技术导向" },
      { text: "业务价值、使用频次、数据准备度、风险和责任人", score: 4, signal: "场景矩阵" },
      { text: "用户数量、功能数量、页面复杂度和传播话题性", score: 1, signal: "产品导向" },
    ],
  },
  {
    id: "q06",
    dimension: "solution",
    scenario: "客户要做“客户反馈自动分类并生成周报”的流程，历史反馈格式不统一。",
    prompt: "哪份首版设计最可交付？",
    options: [
      { text: "先统一输入模板，再由模型分类并生成固定版周报", score: 3, signal: "输入整顿" },
      { text: "校验字段、分类、抽检低置信结果，再汇总并归档", score: 4, signal: "可控流程" },
      { text: "保留原始格式，让模型一次完成清洗、分类和总结", score: 2, signal: "模型整合" },
      { text: "先上线分类功能，周报继续由业务人员手工整理", score: 1, signal: "分段交付" },
    ],
  },
  {
    id: "q07",
    dimension: "solution",
    scenario: "管理层要求 AI 生成一份企业转型方案，但没有提供行业范围、对象或决策用途。",
    prompt: "你会怎样把任务变得可执行？",
    options: [
      { text: "提供三份优秀方案，让模型提炼共同结构后写作", score: 2, signal: "样例引导" },
      { text: "先生成提纲，再由管理层选择需要扩写的章节", score: 3, signal: "分步共创" },
      { text: "指定资深顾问角色，并要求使用正式的行业术语", score: 1, signal: "角色包装" },
      { text: "确认受众、输入、决策问题、输出格式和验收依据", score: 4, signal: "任务工程" },
    ],
  },
  {
    id: "q08",
    dimension: "safety",
    scenario: "销售回复助手的草稿质量稳定，团队希望下周把高意向客户改成自动发送。",
    prompt: "你会批准哪种推进方式？",
    options: [
      { text: "限定低风险模板，保留人工确认并记录误发与承诺", score: 4, signal: "受控放量" },
      { text: "只对评分较高的线索自动发送，并每日抽查结果", score: 3, signal: "分层自动" },
      { text: "先把发送范围控制在老客户，再根据投诉率调整", score: 2, signal: "关系分层" },
      { text: "由销售个人选择是否自动发送，并承担跟进责任", score: 1, signal: "个人授权" },
    ],
  },
  {
    id: "q09",
    dimension: "safety",
    scenario: "客户发来含姓名、电话和合同金额的资料，希望马上用外部模型总结谈判重点。",
    prompt: "你会怎样启动这项工作？",
    options: [
      { text: "先用少量样本验证效果，再根据结果补做安全评审", score: 2, signal: "效果先行" },
      { text: "改用客户指定的账号处理，并保存其书面任务要求", score: 3, signal: "客户授权" },
      { text: "确认处理依据、脱敏范围、可用工具和留痕要求", score: 4, signal: "边界确认" },
      { text: "先提取合同主题和金额区间，避免上传完整原始文件", score: 1, signal: "字段缩减" },
    ],
  },
  {
    id: "q10",
    dimension: "delivery",
    scenario: "客服知识库 Demo 反馈不错，客户要求本月底验收，但双方没有商定成功标准。",
    prompt: "你会怎样定义验收？",
    options: [
      { text: "以核心功能、响应速度和业务负责人满意度为主", score: 2, signal: "功能验收" },
      { text: "锁定问题集、引用率、准确率、转人工率和更新责任", score: 4, signal: "证据验收" },
      { text: "先让一线试用两周，再用使用量和反馈决定结果", score: 3, signal: "试用验收" },
      { text: "沿用同类产品指标，并根据客户规模调整合格线", score: 1, signal: "行业基准" },
    ],
  },
  {
    id: "q11",
    dimension: "delivery",
    scenario: "内部助手上线两周后使用率很低，访谈中有人说结果不错，但入口麻烦且责任不清。",
    prompt: "你会优先做什么？",
    options: [
      { text: "升级模型版本，并增加更多可演示的复杂功能", score: 1, signal: "能力加码" },
      { text: "安排集中培训，同时设置部门使用率考核目标", score: 2, signal: "推广推动" },
      { text: "优化入口和响应速度，再观察一周使用趋势", score: 3, signal: "体验修复" },
      { text: "还原目标任务、使用入口、结果责任和反馈路径", score: 4, signal: "采用诊断" },
    ],
  },
  {
    id: "q12",
    dimension: "delivery",
    scenario: "试点进行到一半，客户提出再接两个系统、增加自动审批和管理驾驶舱。",
    prompt: "你会怎样回应这次变更？",
    options: [
      { text: "记录价值、依赖、风险和工期，再共同决定本期或二期", score: 4, signal: "变更治理" },
      { text: "优先增加驾驶舱，让管理层及时看到试点进展", score: 2, signal: "展示优先" },
      { text: "先接入一个依赖较少的系统，其他需求留到二期", score: 3, signal: "范围折中" },
      { text: "维持原计划到验收结束，再统一讨论新增需求", score: 1, signal: "计划保护" },
    ],
  },
];
