export const dimensionMeta = {
  diagnosis: { label: "业务诊断", short: "诊断", code: "DIA" },
  scenario: { label: "场景判断", short: "场景", code: "SCN" },
  solution: { label: "方案构建", short: "方案", code: "SOL" },
  safety: { label: "风险边界", short: "边界", code: "SAFE" },
  delivery: { label: "推进交付", short: "交付", code: "DEL" },
};

export const questions = [
  {
    id: "q01",
    dimension: "diagnosis",
    scenario: "一家制造企业的老板说：‘我们也要上一个 AI 系统，把效率提起来。’",
    prompt: "你接下来最先做什么？",
    options: [
      { text: "整理一份主流 Agent 平台对比，尽快让老板选型", score: 1, signal: "工具先行" },
      { text: "先做一个酷炫 Demo，让管理层看到 AI 的可能性", score: 2, signal: "演示先行" },
      { text: "访谈管理层、一线与系统负责人，拆出高频任务和证据", score: 4, signal: "诊断先行" },
      { text: "让各部门提交希望 AI 解决的问题，再汇总需求", score: 3, signal: "需求收集" },
    ],
  },
  {
    id: "q02",
    dimension: "diagnosis",
    scenario: "销售团队抱怨‘每天太忙，跟进不过来’，负责人希望做 AI 销售机器人。",
    prompt: "哪项判断最像 FDE？",
    options: [
      { text: "员工抵触新工具，先做一次 AI 培训", score: 1, signal: "表层归因" },
      { text: "先画出现有跟进流程，量化查资料、写摘要和等待时间", score: 4, signal: "流程证据" },
      { text: "直接上线自动外呼，用转化率验证效果", score: 0, signal: "高风险跳跃" },
      { text: "用大模型生成更多销售话术，先提升内容产量", score: 2, signal: "局部提效" },
    ],
  },
  {
    id: "q03",
    dimension: "scenario",
    scenario: "客户同时提出商品文案、差评分析、库存预测和自动投流四个 AI 场景。",
    prompt: "首期试点你会优先推荐哪一组？",
    options: [
      { text: "库存预测 + 自动投流，价值最大，最能打动老板", score: 1, signal: "价值幻觉" },
      { text: "四个一起做，避免后面重复建设", score: 0, signal: "范围失控" },
      { text: "商品文案 + 差评分析，数据易准备、结果可校验", score: 4, signal: "可行试点" },
      { text: "只做商品文案，因为生成式 AI 最擅长写作", score: 2, signal: "单点工具" },
    ],
  },
  {
    id: "q04",
    dimension: "scenario",
    scenario: "企业有 30 份产品资料，希望知识库助手回答售前问题。资料中存在两个价格版本。",
    prompt: "正确的推进顺序是什么？",
    options: [
      { text: "先全部上传，用提示词要求模型优先采用最新版", score: 1, signal: "技术补洞" },
      { text: "先确认版本、权限和适用范围，再设计测试问题", score: 4, signal: "资料治理" },
      { text: "让 AI 自动判断哪个价格更合理", score: 0, signal: "越权判断" },
      { text: "隐藏价格问题，先上线其他问答", score: 2, signal: "局部规避" },
    ],
  },
  {
    id: "q05",
    dimension: "scenario",
    scenario: "你要从 10 个候选场景里选择第一个能跑起来的企业 AI 场景。",
    prompt: "哪组指标最有判断力？",
    options: [
      { text: "模型参数、上下文长度、榜单排名、调用价格", score: 1, signal: "模型中心" },
      { text: "老板重视程度、预算、传播性、技术新颖度", score: 2, signal: "展示中心" },
      { text: "业务价值、使用频次、数据准备度、复杂度、风险", score: 4, signal: "场景矩阵" },
      { text: "开发速度、界面效果、功能数量、供应商品牌", score: 0, signal: "产品幻觉" },
    ],
  },
  {
    id: "q06",
    dimension: "solution",
    scenario: "客户要做一个‘客户反馈自动分类并生成周报’的工作流。",
    prompt: "哪份设计更接近可交付方案？",
    options: [
      { text: "上传数据 → AI 分析 → 输出周报", score: 1, signal: "黑箱流程" },
      { text: "触发 → 字段校验 → 分类 → 低置信度转人工 → 汇总 → 归档", score: 4, signal: "可控工作流" },
      { text: "接入最强模型，让它自主规划所有步骤", score: 0, signal: "自主迷信" },
      { text: "先写一个很长的 Prompt，把所有要求一次说完", score: 2, signal: "提示词堆叠" },
    ],
  },
  {
    id: "q07",
    dimension: "solution",
    scenario: "你需要把‘做一份企业 AI 转型方案’改造成模型可执行任务。",
    prompt: "最关键的补充是什么？",
    options: [
      { text: "要求模型扮演全球顶级战略顾问", score: 1, signal: "角色包装" },
      { text: "加入更多行业术语，让输出显得专业", score: 0, signal: "术语包装" },
      { text: "明确受众、输入、步骤、输出格式、验收标准与未知项", score: 4, signal: "任务工程" },
      { text: "提供一份竞品方案，让模型照着改写", score: 2, signal: "模板依赖" },
    ],
  },
  {
    id: "q08",
    dimension: "safety",
    scenario: "销售跟进工作流已能自动生成客户回复，团队希望下一步直接自动发送。",
    prompt: "你如何处理？",
    options: [
      { text: "先保留人工确认，并记录误发、承诺与低置信度风险", score: 4, signal: "人工闸门" },
      { text: "只给高意向客户自动发送，风险可以接受", score: 1, signal: "风险赌注" },
      { text: "设置更低的 temperature 就可以全自动", score: 0, signal: "参数迷信" },
      { text: "让销售自行决定是否开启自动发送", score: 2, signal: "责任下放" },
    ],
  },
  {
    id: "q09",
    dimension: "safety",
    scenario: "客户把含姓名、电话、合同金额的原始资料发给你，要求马上上传公共模型分析。",
    prompt: "FDE 的正确动作是什么？",
    options: [
      { text: "只要不公开分享对话链接就可以上传", score: 0, signal: "隐私误区" },
      { text: "先确认授权、脱敏、数据边界、留痕与可用工具", score: 4, signal: "合规前置" },
      { text: "先上传一小部分，验证效果后再谈安全", score: 1, signal: "先斩后奏" },
      { text: "让客户书面承诺自行承担全部风险", score: 2, signal: "甩锅合规" },
    ],
  },
  {
    id: "q10",
    dimension: "delivery",
    scenario: "一个客服知识库 Demo 演示效果不错，客户问：‘怎么验收？’",
    prompt: "哪种回答最专业？",
    options: [
      { text: "客户满意就算通过，AI 很难用固定标准衡量", score: 1, signal: "主观验收" },
      { text: "以功能完整、界面流畅和回复速度作为标准", score: 2, signal: "产品验收" },
      { text: "定义标准问题准确率、引用率、转人工率、响应时间和更新机制", score: 4, signal: "可测验收" },
      { text: "先上线试用，真实数据自然会告诉我们答案", score: 0, signal: "无标准上线" },
    ],
  },
  {
    id: "q11",
    dimension: "delivery",
    scenario: "Demo 上线两周后，业务人员几乎没人使用。",
    prompt: "你优先检查什么？",
    options: [
      { text: "模型是否需要升级到最新版本", score: 1, signal: "模型归因" },
      { text: "入口、真实使用场景、培训、结果可信度和反馈闭环", score: 4, signal: "客户成功" },
      { text: "是否应该增加积分和排行榜刺激使用", score: 2, signal: "运营补丁" },
      { text: "用户不愿改变习惯，项目已经没有继续价值", score: 0, signal: "交付放弃" },
    ],
  },
  {
    id: "q12",
    dimension: "delivery",
    scenario: "试点进行到一半，客户提出再接两个系统、增加自动审批和老板驾驶舱。",
    prompt: "你怎么回应最合适？",
    options: [
      { text: "先答应，客户满意是最重要的", score: 0, signal: "范围讨好" },
      { text: "全部拒绝，严格按最初方案做完", score: 2, signal: "僵硬交付" },
      { text: "记录变更，评估价值、依赖、风险和工期，再共同确认是否进入二期", score: 4, signal: "变更治理" },
      { text: "先把驾驶舱做出来，方便老板看到成果", score: 1, signal: "展示优先" },
    ],
  },
];
