import assert from 'node:assert/strict';
import fs from 'node:fs';
const read = (path) => fs.readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');
const service = read('deploy/fde-network.service');
assert.match(service, /FDE_NETWORK_DB=\/var\/lib\/fde-network\/network\.db/);
assert.match(service, /FDE_NETWORK_HOST=127\.0\.0\.1/);
assert.match(service, /FDE_NETWORK_PORT=8766/);
assert.match(service, /ReadWritePaths=\/var\/lib\/fde-network/);
assert.match(service, /ProtectSystem=strict/);
const nginx = read('deploy/fde.onex.plus.nginx.conf');
const localServer = read('tests/fde-local-integration-server.mjs');
assert.match(nginx, /location \^~ \/api\/network\//);
assert.match(nginx, /proxy_pass http:\/\/127\.0\.0\.1:8766/);
assert.match(nginx, /location = \/api\/network\/config/);
assert.match(nginx, /location \^~ \/api\/network\/public\//);
assert.match(nginx, /location ~ \^\/talents\/\[a-z0-9\]/);
assert.match(nginx, /try_files \/talents\/profile\.html =404/);
assert.match(localServer, /TALENT_PROFILE_PATH/);
assert.match(localServer, /talents', 'profile\.html/);
assert.match(localServer, /FDE_NETWORK_API_URL/);
const install = read('deploy/install-or-update.sh');
assert.match(install, /NETWORK_DATA="\/var\/lib\/fde-network"/);
assert.match(install, /fde-network\.service/);
assert.match(install, /fde_network\.db import connect, initialize/);
assert.match(install, /127\.0\.0\.1:8766\/api\/network\/health/);
const readme = read('README.md');
assert.match(readme, /FDE_NETWORK_DB=\/tmp\/fde-network\.db/);
assert.match(readme, /import_talents[\s\S]{0,180}--dry-run/);
assert.match(readme, /set-flag network_enabled true/);
assert.match(readme, /set-flag network_enabled false/);
console.log('FDE network deployment contract passed');
