map $ssl_preread_server_name $fde_tls_backend {
    fde.onex.plus 127.0.0.1:8443;
    default       127.0.0.1:1443;
}

server {
    listen 443;
    listen [::]:443;
    proxy_pass $fde_tls_backend;
    ssl_preread on;
    proxy_connect_timeout 10s;
    proxy_timeout 300s;
}
