server {
    listen 80;
    listen [::]:80;
    server_name fde.onex.plus;

    root /var/www/fde.onex.plus;
    index index.html;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/fde.onex.plus;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
