server {
    listen 80;
    listen [::]:80;
    server_name fde.onex.plus;

    root /var/www/fde.onex.plus;
    index index.html;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/fde.onex.plus;
    }

    location = /robots.txt {
        default_type text/plain;
        try_files $uri =404;
    }

    location = /sitemap.xml {
        default_type application/xml;
        try_files $uri =404;
        types { }
    }

    location = /llms.txt {
        default_type text/plain;
        try_files $uri =404;
    }

    location = /34c6fa8d839d4074e38e57038dde09e7.txt {
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
